name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Apply code formatting
        run: ./gradlew spotlessApply

      - name: Build with Gradle
        run: ./gradlew clean build --parallel

      - name: Run tests with Gradle
        run: ./gradlew test

      - name: Upload build artefacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artefacts
          path: build/libs/*

  verify-signature:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download build artefacts
        uses: actions/download-artifact@v3
        with:
          name: build-artefacts

      - name: Sign artefacts
        env:
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_SECRET_KEY_RING_FILE: ${{ secrets.SIGNING_SECRET_KEY_RING_FILE }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
        run: |
          echo $SIGNING_SECRET_KEY_RING_FILE | base64 --decode > /tmp/secring.gpg
          ./gradlew signArchives -Psigning.keyId=$SIGNING_KEY_ID -Psigning.secretKeyRingFile=/tmp/secring.gpg -Psigning.password=$SIGNING_PASSWORD

      - name: Upload signed artefacts
        uses: actions/upload-artifact@v3
        with:
          name: signed-artefacts
          path: build/libs/*

  start-and-test:
    runs-on: ubuntu-latest
    needs: verify-signature

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download signed artefacts
        uses: actions/download-artifact@v3
        with:
          name: signed-artefacts

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Verify artefacts
        run: |
          gpg --verify build/libs/*.asc

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Start application in background
        run: ./gradlew :bootstrap:bootRun &

      - name: Wait for application to start
        run: |
          echo "Waiting for application to start..."
          until curl --output /dev/null --silent --head --fail http://localhost:8080/actuator/health; do
            echo "Waiting for application to be up..."
            sleep 5
          done

      - name: Check if application is running
        run: curl --retry 10 --retry-delay 5 --retry-connrefused http://localhost:8080/actuator/health

      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}

      - name: Run API tests
        run: |
          postman collection run "33012353-55f2ea80-2347-4876-9d26-6444ca00493c" -e "33012353-fb862ff7-d879-47ef-af2f-b8ba67337e97"

      - name: Stop application
        run: pkill -f 'gradlew'

      - name: Upload Logs
        uses: actions/upload-artifact@v3
        with:
          name: logs
          path: build/reports/tests/test/index.html