name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Run tests with Gradle
        run: ./gradlew test

  start-and-test:
    runs-on: ubuntu-latest
    needs: build # Assure que le job 'build' est exécuté avant 'start-and-test'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Start application in background
        run: ./gradlew :bootstrap:bootRun &

      - name: Wait for application to start
        run: |
          echo "Waiting for application to start..."
          sleep 30 # Ajustez cette durée selon le temps que prend votre application à démarrer

      - name: Run API tests
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
          postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
          postman collection run "33012353-55f2ea80-2347-4876-9d26-6444ca00493c" -e "33012353-fb862ff7-d879-47ef-af2f-b8ba67337e97"

      - name: Stop application
        run: pkill -f 'gradlew' # Cette commande arrête l'application démarrée
