name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: List build/libs directory
        run: ls -l build/libs

      - name: Verify that the JAR file exists
        run: |
          if [ ! -f "build/libs/realworld-plain.jar" ]; then
            echo "Error: build/libs/realworld-plain.jar not found."
            exit 1
          fi

      - name: Set up GPG
        run: |
          echo "$GPG_PRIVATE_KEY" | base64 --decode > private.key
          gpg --batch --import private.key
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Sign artifacts
        run: |
          gpg --pinentry-mode loopback --batch --yes --passphrase "${{ secrets.GPG_PASSPHRASE }}" --output build/libs/realworld-plain.jar.sig --detach-sign build/libs/realworld-plain.jar

      - name: Upload signature and artifact
        uses: actions/upload-artifact@v3
        with:
          name: signed-artifact
          path: build/libs/realworld-plain.jar.sig

      - name: Upload jar
        uses: actions/upload-artifact@v3
        with:
          name: built-jar
          path: build/libs/realworld-plain.jar

      - name: Run tests with Gradle
        run: ./gradlew test

  verify-signature:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download signed artifact
        uses: actions/download-artifact@v3
        with:
          name: signed-artifact
          path: build/libs/

      - name: Download JAR
        uses: actions/download-artifact@v3
        with:
          name: built-jar
          path: build/libs/

      - name: Set up GPG
        run: |
          echo "$GPG_PUBLIC_KEY" > public.key
          gpg --batch --import public.key
        env:
          GPG_PUBLIC_KEY: ${{ secrets.GPG_PUBLIC_KEY }}

      - name: Verify artifact signature
        run: gpg --verify build/libs/realworld-plain.jar.sig build/libs/realworld-plain.jar

  start-and-test:
    runs-on: ubuntu-latest
    needs: [build, verify-signature]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Start application in background
        run: ./gradlew :bootstrap:bootRun &

      - name: Wait for application to start
        run: |
          echo "Waiting for application to start..."
          sleep 60

      - name: Check if application is running
        run: curl --retry 10 --retry-delay 5 --retry-connrefused http://localhost:8080/actuator/health

      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}

      - name: Run API tests
        run: |
          postman collection run "33012353-55f2ea80-2347-4876-9d26-6444ca00493c" -e "33012353-fb862ff7-d879-47ef-af2f-b8ba67337e97"

      - name: Stop application
        run: pkill -f 'gradlew'

      - name: Upload Logs
        uses: actions/upload-artifact@v3
        with:
          name: logs
          path: build/reports/tests/test/index.html