name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew clean build

    - name: Run tests with Gradle
      run: ./gradlew test

    - name: Start application
      run: ./gradlew :bootstrap:bootRun
      
  automated-api-tests:
    runs-on: ubuntu-latest
    needs: build  # Assure que le job 'build' est exécuté avant 'automated-api-tests'

    steps:
    - uses: actions/checkout@v3

    - name: Install Postman CLI
      run: |
        curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

    - name: Login to Postman CLI
      run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}

    - name: Run API tests
      run: |
        postman collection run "33012353-55f2ea80-2347-4876-9d26-6444ca00493c" -e "33012353-fb862ff7-d879-47ef-af2f-b8ba67337e97"
